name: Your New Jekyll Site
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
encoding: utf-8

permalink: /:categories/:title/

# github settings
baseurl:

translations:
  en:
    logo:
      name: "Marriage & Family For Christ"
      slogan: ""
    side_menu:
      whats_new: "What's New"
    header:
      about: 'About us'
      youth: "Youth"
      mer: "Marriage"
      mag: "Publications"
      news: "News"
  zh-hk:
    logo:
      name: " 澳洲家庭更新協會"
      slogan: "建立生命品格， 活像基督的家新人"
    side_menu:
      whats_new: "近期更新"
    header:
      about: "關於家新"
      youth: "婚前及青年關係事工"
      mer: "夫婦營及婚姻事工"
      mag: "文字及影音"
      news: "聚會"
